name: Pylint
on: [push, pull_request]
jobs:
  pylint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python 3.10 x64
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          architecture: 'x64'
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
      - name: install dependencies
        run: uv sync --group test
      - name: Run Pylint
        run: uv run pylint --recursive=y --errors-only --jobs=0 "$PWD"
